# Generated by Django 2.0.2 on 2019-10-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=64)),
                ('province', models.CharField(blank=True, default='', max_length=32)),
                ('property_type', models.CharField(blank=True, choices=[('PL', 'Place'), ('CA', 'Car'), ('EQ', 'Equipment')], max_length=2, null=True)),
            ],
        ),
    ]
