# Generated by Django 2.0.2 on 2019-10-04 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0002_auto_20191004_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('inspection_date', models.DateTimeField(blank=True, null=True, verbose_name='when the inspection occured')),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('FI', 'Finalized')], default='DR', max_length=2, null=True)),
                ('inspected_property', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.Property')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
