# Generated by Django 2.0.2 on 2019-10-04 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_inspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('picture', models.ImageField(null=True, upload_to='inspections_files/')),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('inspection', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='property.Inspection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
