# Generated by Django 2.0.2 on 2019-10-04 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_inspectionfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('signature', models.ImageField(null=True, upload_to='report_signatures/')),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('SI', 'Signed'), ('FI', 'Finalized')], default='DR', max_length=2, null=True)),
                ('inspection', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='property.Inspection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
