# Generated by Django 2.0.2 on 2019-10-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='when the inspection occured'),
        ),
    ]
