# Generated by Django 2.0.2 on 2019-10-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20191004_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='properties_images/'),
        ),
    ]
