# Generated by Django 2.0.2 on 2019-10-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_file',
            field=models.FileField(null=True, upload_to='reports/'),
        ),
    ]
