# Generated by Django 2.0.2 on 2019-10-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_report_report_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='description',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='property',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='property',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
