# Generated by Django 2.0.2 on 2019-10-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20191030_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
