# Generated by Django 2.0.2 on 2019-10-31 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_inspectionitem_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionfile',
            name='notes',
        ),
        migrations.AddField(
            model_name='inspectionfile',
            name='inspection_item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_files', to='property.InspectionItem'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='when the inspection occured'),
        ),
        migrations.AlterField(
            model_name='inspectionfile',
            name='inspection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_files', to='property.Inspection'),
        ),
    ]
