# Generated by Django 2.0.2 on 2019-11-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_remove_inspectiontemplateitem_inspection_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='tenant_email',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='inspection',
            name='tenant_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='inspection',
            name='tenant_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='tenant_phone',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
